base_model: axolotl-ai-co/gpt-oss-120b-dequantized

hub_model_id: baseten-admin/multilingual-sft-gpt-oss-120b-longcontext
hub_strategy: end  # only push the final model, don't push intermediate checkpoints

use_kernels: false

dp_shard_size: 8
dp_replicate_size: 2

plugins:
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin

experimental_skip_move_to_device: true  # prevent OOM by NOT putting model to GPU before sharding

datasets:
  - path: HuggingFaceH4/Multilingual-Thinking
    type: chat_template
    field_thinking: thinking
    template_thinking_key: thinking

dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: ./outputs/gpt-oss-out/
save_only_model: true  # triggers a lot of sync operations on baseten

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 3

optimizer: adamw_torch_fused  # 8bit optimizers do not work with FSDP2 offload
lr_scheduler: constant_with_warmup
learning_rate: 3e-6

warmup_ratio: 0.1

bf16: true
tf32: true

flash_attention: true
attn_implementation: kernels-community/vllm-flash-attn3

gradient_checkpointing: true
activation_offloading: true

logging_steps: 1
saves_per_epoch: 1

special_tokens:
eot_tokens:
  - "<|end|>"
  - "<|return|>"

gc_steps: -1

fsdp_version: 2
fsdp_config:
  offload_params: true
  state_dict_type: FULL_STATE_DICT
  auto_wrap_policy: TRANSFORMER_BASED_WRAP
  transformer_layer_cls_to_wrap: GptOssDecoderLayer
  reshard_after_forward: 8
  cpu_ram_efficient_loading: true

use_wandb: true
wandb_project: Axolotl GPT OSS 120b 2node longcontext
wandb_entity: philipkiely-baseten